update flake

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -45,9 +45,16 @@ jobs:
       - name: Verify environment
         run: conda list
 
-      # ----------------- 6. Lint code with flake8 -------------------
+     # ----------------- 6. Check where flake8 is -------------------
+      - name: Check where flake8 is
+        run: |
+          source activate ci-environment
+          which flake8 || echo "flake8 not found"
+
+      # ----------------- 7. Lint code with flake8 -------------------
       - name: Lint with flake8
         run: |
+          source activate ci-environment
           echo "Running flake8 linting..."
           flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
 
